"""Create tb_inspection model

Revision ID: 1ef212d31a90
Revises: c941f3b5e4b8
Create Date: 2025-02-25 22:49:40.802343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ef212d31a90'
down_revision = 'c941f3b5e4b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_inspection',
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('trx_id', sa.String(length=50), nullable=False),
    sa.Column('reg_no', sa.String(length=50), nullable=False),
    sa.Column('remark_reg_no', sa.String(length=255), nullable=True),
    sa.Column('engine_no', sa.String(length=50), nullable=False),
    sa.Column('remark_engine_no', sa.String(length=255), nullable=True),
    sa.Column('chassis_no', sa.String(length=50), nullable=False),
    sa.Column('remark_chassis_no', sa.String(length=255), nullable=True),
    sa.Column('front_fid', sa.String(length=255), nullable=True),
    sa.Column('back_fid', sa.String(length=255), nullable=True),
    sa.Column('engine_no_fid', sa.String(length=255), nullable=True),
    sa.Column('chassis_no_fid', sa.String(length=255), nullable=True),
    sa.Column('officer_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('inspection_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_inspection')
    # ### end Alembic commands ###
