"""adding inspection to user

Revision ID: 5b9ad7dcb6ca
Revises: 1ef212d31a90
Create Date: 2025-02-25 23:01:54.651021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b9ad7dcb6ca'
down_revision = '1ef212d31a90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_inspection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('officer', sa.String(length=255), nullable=True))
        batch_op.drop_constraint('tb_inspection_officer_id_fkey', type_='foreignkey')
        batch_op.drop_column('officer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_inspection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('officer_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('tb_inspection_officer_id_fkey', 'users', ['officer_id'], ['id'])
        batch_op.drop_column('officer')

    # ### end Alembic commands ###
