"""change inspection to user

Revision ID: bb355da3e4e7
Revises: 5b9ad7dcb6ca
Create Date: 2025-02-25 23:56:06.498159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb355da3e4e7'
down_revision = '5b9ad7dcb6ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_inspection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('front_image_base64', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('back_image_base64', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('engine_no_image_base64', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('chassis_no_image_base64', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reg_no_image_base64', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_inspection', schema=None) as batch_op:
        batch_op.drop_column('reg_no_image_base64')
        batch_op.drop_column('chassis_no_image_base64')
        batch_op.drop_column('engine_no_image_base64')
        batch_op.drop_column('back_image_base64')
        batch_op.drop_column('front_image_base64')

    # ### end Alembic commands ###
